version: '3.1'

services:
  mlnx_ofed:
    image: cdac_mlnxofed:23.10-3.2.2.0
    container_name: ofed_driver
    privileged: true
    volumes:
      - /run/mellanox/drivers:/run/mellanox/drivers:shared
      - /etc/network:/etc/network
      - /etc:/host/etc
      - /lib/udev:/host/lib/udev
    tty: true
    hostname: ofed
    network_mode: host

networks:
  host:
